### ISSUE TITLE
Stream Bark Speed

### ISSUE THREAD

**Issue by Bambuuai** [gayanMatch/StreamBark#1]
it's still slow in my pc.
are there any other way faster than this?

**Comment by gayanMatch** [comment]
Current model is not totally streamlined.
Maybe total streamming will provide faster speed

**Comment by Bambuuai** [comment]
Could you show me that?

**Comment by gayanMatch** [comment]
Contact me.
It's on my private.

**Comment by Bambuuai** [comment]
Perfect
